name: client

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    build:
        name: Publish NPM
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: "latest"

            - name: Check if package version changed
              id: check_publish
              run: bun ./scripts/check-version.ts

            - run: bun install --frozen-lockfile
              working-directory: ./client
            - run: bun run build
              working-directory: ./client

            - uses: actions/setup-node@v6
              if: env.publish == 'true'
              with:
                  node-version: "latest"
                  registry-url: "https://registry.npmjs.org"

            - run: npm publish --provenance --access public
              if: env.publish == 'true'
              working-directory: ./client
