name: server

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    build:
        name: Publish GHCR
        runs-on: ubuntu-latest
        env:
            IMAGE_BASE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

        steps:
            - uses: actions/checkout@v7
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v4
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: "latest"

            - name: Check if package version changed
              id: check_publish
              run: bun ./scripts/check-version.ts

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v6
              with:
                  images: ${{ env.IMAGE_BASE }}
                  tags: |
                      type=semver,value=${{ env.version }},pattern=v{{version}},enable=${{ env.publish == 'true' }}
                      type=semver,value=${{ env.version }},pattern=v{{major}}.{{minor}},enable=${{ env.publish == 'true' }}
                      type=semver,value=${{ env.version }},pattern=v{{major}},enable=${{ env.publish == 'true' }}
                      type=raw,value=latest,enable=${{ env.publish == 'true' }}
                      type=raw,value=git,enable=${{ env.publish != 'true' }}
                      type=sha,format=short,enable=${{ env.publish != 'true' }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v7
              with:
                  context: .
                  push: true
                  build-args: BUILD_VERSION=${{ env.version }}
                  tags: ${{ steps.meta.outputs.tags }}
