name: server

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    test:
        name: Test Srver
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
            - name: Build Docker image
              run: docker build --build-arg BUILD_VERSION=pr-${{ github.event.pull_request.number }} -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:pr-${{ github.event.pull_request.number }} .

            - name: Push Docker image
              if: github.actor == github.repository_owner
              run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:pr-${{ github.event.pull_request.number }}